language: android
jdk: oraclejdk8

env:
  global:
    # Initiating clean Gradle output
    - TERM=dumb
    # Amount of memory granted to Gradle JVM
    - GRADLE_OPTS="-Xmx1024m -XX:MaxPermSize=512m"

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17

  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

addons:
  apt:
    packages:
    - libstdc++6:i386
    - lib32z1
    - expect

before_install:
 - chmod +x gradlew

# script: ./gradlew connectedCheckGooglePlayRelease
